import type { Metadata } from "next"
import Image from "next/image"
import { notFound } from "next/navigation"
import { InquiryForm } from "@/components/inquiry-form"
import { formatPrice, getProperties, getProperty } from "@/lib/properties"

export async function generateStaticParams(){const {items}=await getProperties();return items.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {item}=await getProperty((await params).slug);return item?{title:item.title,description:item.description,openGraph:{images:[item.images[0].src]}}:{title:"Property not found"}}
export default async function PropertyPage({params}:{params:Promise<{slug:string}>}){const {item,source}=await getProperty((await params).slug);if(!item)notFound();const jsonLd={"@context":"https://schema.org","@type":"Residence",name:item.title,description:item.description,image:item.images.map(i=>i.src),address:{"@type":"PostalAddress",addressLocality:item.location},offers:{"@type":"Offer",price:item.price,priceCurrency:"EUR"}};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><section className="property-hero"><div className="property-visual"><Image src={item.images[0].src} alt={item.images[0].alt} fill priority sizes="(max-width: 850px) 100vw, 68vw"/></div><div className="property-summary"><p className="eyebrow">{item.location}</p><h1>{item.title}</h1><p className="price">{formatPrice(item)}</p><div className="facts"><span>{item.bedrooms} beds</span><span>{item.bathrooms} baths</span><span>{item.builtArea} m²</span></div><p className="source-note">Source: {source}</p></div></section><section className="property-body"><div><p className="eyebrow">The residence</p><h2>A home shaped around everyday life</h2><p>{item.description}</p><h2>Details</h2><ul className="feature-list">{item.features.map(f=><li key={f}>{f}</li>)}</ul></div><aside><p className="eyebrow">Private viewing</p><h2>Experience it in person</h2><InquiryForm propertyId={item.id}/></aside></section></>}
