import Image from "next/image"
import Link from "next/link"
import { ArrowRight } from "lucide-react"
import { PropertyCard } from "@/components/property-card"
import { getProperties } from "@/lib/properties"

export default async function Home() {
  const { items, source } = await getProperties()
  return <><section className="hero"><Image src={items[0].images[0].src} alt={items[0].images[0].alt} fill priority sizes="100vw"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow light">Marbella · Property & relocation</p><h1>Exceptional homes.<br/>Thoughtfully found.</h1><p>Local intelligence, discreet representation, and a calmer way to move.</p><div><Link className="button light-button" href="/buy">Explore homes</Link><Link className="text-link light" href="/matchmaker">Tell us what fits <ArrowRight/></Link></div></div></section><section className="search-panel"><form action="/buy"><label>Location<select name="area"><option value="">All areas</option><option value="golden-mile">Golden Mile</option><option value="nueva-andalucia">Nueva Andalucía</option><option value="benahavis">Benahavís</option></select></label><label>Bedrooms<select name="beds"><option value="">Any</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label><label>Maximum price<select name="max"><option value="">No maximum</option><option value="1000000">€1M</option><option value="2000000">€2M</option><option value="4000000">€4M</option></select></label><button className="button">Search properties</button></form></section><section className="section"><div className="section-head"><div><p className="eyebrow">Curated portfolio</p><h2>Homes with a point of view</h2></div><Link className="text-link" href="/buy">View all <ArrowRight/></Link></div><div className="property-grid">{items.slice(0,3).map((property,index)=><PropertyCard key={property.id} property={property} priority={index===0}/>)}</div><p className="source-note">Property source: {source === "captemos" ? "Live CapteMos feed" : "Demo feed"}</p></section><section className="manifesto"><p className="eyebrow light">A considered search</p><h2>Property is only part of the move.</h2><p>We combine homes, neighborhoods, schools, logistics, and everyday life into one clear recommendation.</p><Link className="button light-button" href="/relocation">Discover relocation</Link></section><section className="section editorial"><div><p className="eyebrow">Private Matchmaker</p><h2>Less scrolling.<br/>More relevance.</h2></div><div><p>Share your budget, lifestyle, family needs, and timeframe. We will turn them into a focused brief and a shortlist built around how you want to live.</p><Link className="text-link" href="/matchmaker">Start your brief <ArrowRight/></Link></div></section></>
}
